# Generated by Django 4.0.1 on 2022-01-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questão',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=255)),
                ('alternativa1', models.CharField(max_length=255)),
                ('alternativa2', models.CharField(max_length=255)),
                ('alternativa3', models.CharField(max_length=255)),
                ('alternativacorreta', models.CharField(max_length=255)),
            ],
        ),
    ]
