# Generated by Django 4.0.1 on 2022-01-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questão',
            new_name='questao',
        ),
    ]
