# Generated by Django 4.0.1 on 2022-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0002_rename_questão_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='correto',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='respondido',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
