# Generated by Django 4.0.1 on 2022-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0003_questao_correto_questao_respondido'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questoes', models.ManyToManyField(to='correcao.questao')),
            ],
        ),
    ]
