# Generated by Django 4.0.1 on 2022-01-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0004_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='questoes',
        ),
        migrations.AddField(
            model_name='lista',
            name='numero',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='listas',
            field=models.ManyToManyField(to='correcao.lista'),
        ),
    ]
